### ISSUE TITLE
Change , to .

### ISSUE THREAD

**Issue by edu-nixon** [changLiuUNSW/angular-numeric-input#1]
Hi, thanks for this awesome plugin.

I want to change the **,** to a **.**

I have tried some things but with no success, could you please help me? Thanks.

**Comment by edu-nixon** [comment]
Ok, I found that if I added the i18n of my country the numbers appear with a dot.

https://cdnjs.cloudflare.com/ajax/libs/angular-i18n/1.5.8/angular-locale_es-cl.min.js

But it seems like the plugin doesn't work with that :/

**Comment by changLiuUNSW** [comment]
@Eduardo-Julio Can you replicate this issue in the Plunker?

**Comment by edu-nixon** [comment]
Hi @changLiuUNSW , I ended up using another directive so you can close this if you want, or I can replicate the issue if you still want to fix it

**Comment by changLiuUNSW** [comment]
@Eduardo-Julio  I think my directive does not support i18n at this moment. 

That will be good if you can replicate the issue in the Plunker. Thanks :)

**Comment by changLiuUNSW** [comment]
closed because lack of todos
